2025-05-22 19:49:07 [ERROR] classifier.production:wrapper:274: [2m2025-05-23T01:49:07.148930Z[0m [[31m[1merror    [0m] [1mOperation failed              [0m [[0m[1m[34mclassifier.production[0m][0m [36mduration_seconds[0m=[35m0.009[0m [36merror[0m=[35m'[Errno 32] Broken pipe'[0m [36merror_type[0m=[35mBrokenPipeError[0m [36mfunction[0m=[35mprocess_talks_with_progress[0m [36moperation[0m=[35mbulk_talk_processing[0m
2025-05-22 19:49:07 [ERROR] classifier:main:702: {"error": "[Errno 32] Broken pipe", "error_type": "BrokenPipeError", "event": "Application error", "logger": "classifier", "level": "error", "timestamp": "2025-05-23T01:49:07.150855Z", "exception": "Traceback (most recent call last):\n  File \"/Users/davehedengren/code/conference-talk-challenge-classifier/classifier_production.py\", line 680, in main\n    process_talks_with_progress(\n  File \"/Users/davehedengren/code/conference-talk-challenge-classifier/utils/logging_config.py\", line 263, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/davehedengren/code/conference-talk-challenge-classifier/classifier_production.py\", line 571, in process_talks_with_progress\n    progress_bar = tqdm(\n                   ^^^^^\n  File \"/Users/davehedengren/code/conference-talk-challenge-classifier/.venv/lib/python3.12/site-packages/tqdm/std.py\", line 1096, in __init__\n    self.sp = self.status_printer(self.fp)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/davehedengren/code/conference-talk-challenge-classifier/.venv/lib/python3.12/site-packages/tqdm/std.py\", line 449, in status_printer\n    getattr(sys.stdout, 'flush', lambda: None)()\nBrokenPipeError: [Errno 32] Broken pipe"}
